
language: r
sudo: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE


before_install:
  - wget https://github.com/google/protobuf/archive/v2.5.0.tar.gz
  - tar -zxvf v2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure; make; make check; make install --prefix=~/protobuf


branches:
  only:
    - master
    - dev
    - travis

notifications:
  email:
    recipients:
    - schloerke@gmail.com
    on_success: change
    on_failure: change
