
language: r
sudo: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

addons:
  apt:
    packages:
      - libprotobuf9

branches:
  only:
    - master
    - dev
    - travis

notifications:
  email:
    recipients:
    - schloerke@gmail.com
    on_success: change
    on_failure: change
